Redirection
facebookincubator/go2chef pull request #50
Opened 2022-02-01 14:17 UTC by Zeltserj

Adding redirection to solve https://github.com/facebookincubator/go2chef/issues/41
Simply add to your step in the configuration an `output` dir, with `out` and `err` as keys and paths as values, for example:

```
{
  "steps": [
    {
      "type": "go2chef.step.command",
      "name":"ls",
      "command": ["ls"],
      "output": {
        "out": "out.txt",
        "err": "err.txt"
      }
    }
  ]
}
```

2022-02-02 18:11 UTC, gogsbread commented on plugin/step/command/command.go
> +		}
Guess the newer way to do this is `errors.Is(err, fs.ErrNotExist)`.

2022-02-02 18:19 UTC, gogsbread commented on plugin/step/command/command.go
> +	return true
this function fails default open(`true`) which does not sound right? i.e it will say the file exists for all other failures of `stat` call

2022-02-02 19:01 UTC, gogsbread commented on plugin/step/command/command.go
> +		cmd.Stderr = os.Stderr
if output file path is same as error path and if both are not empty, we should probably do something like `cmd.Stderr = cmd.Stdout`? Basically, the user wanted something like `2>&1`

2022-02-02 19:03 UTC, gogsbread commented on plugin/step/command/command.go
> +		return nil, err
nit: move `create` after `setOutputWrite` to maintain the reading flow as that of  `setOutputRedirect -> setOutputWrite`?

2022-02-02 19:21 UTC, gogsbread commented on plugin/step/command/command.go
> +		}
Instead of doing it this way, how about we `stat` and if that returns `ENOENT`(fs.ErrNotExist?), we create the directory and then carry on opening the file with `O_CREATE`? something like

```
if _, err := os.Stat(name); err != nil && errors.Is(err, fs.ErrNotExist) {
  os.MkdirAll(filepath.Dir(p), 0770);
  ...
}
file, err = os.OpenFile(path, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0666)
```

2022-02-02 19:21 UTC, gogsbread commented on plugin/step/command/command.go
> +	return true
ah.. i think I see why you did this way. Looks like you are opening the file in `O_CREATE` flag even if this returns `true` to cover the edge cases. I added another suggestion at the bottom. lmk what you think.

2022-02-02 19:24 UTC, gogsbread commented on plugin/step/command/command.go
> +func setOutputWrite(path string) (io.Writer, *os.File, error) {
just returning writer and err should suffice right? basically, the api would return that you converted the string path to a io writer.

2022-02-02 19:27 UTC, gogsbread commented on plugin/step/command/command.go
> +	return io.MultiWriter(file, os.Stdout), file, nil
writing to `os.stdout` would create a `tee` behavior; is that intended?

2022-02-02 19:27 UTC, gogsbread requested changes
few comments from my observation

2022-02-03 06:14 UTC, Zeltserj commented on plugin/step/command/command.go
> +func setOutputWrite(path string) (io.Writer, *os.File, error) {
I'm returning the file so I can close it in `Execute` function (otherwise it can't be written to)

2022-02-03 15:36 UTC, Zeltserj commented on plugin/step/command/command.go
> +	return io.MultiWriter(file, os.Stdout), file, nil
I understood the relevant use case was to reuse the output for other commands, so getting them in a file was the point and having them in stdout as well seemed logical. did i miss something?

2022-02-03 18:25 UTC, Zeltserj commented on plugin/step/command/command.go
> +		cmd.Stderr = os.Stderr
Added.

2022-02-05 23:24 UTC, gogsbread commented on plugin/step/command/command.go
> +
nit: extra whitespace

2022-02-05 23:25 UTC, gogsbread commented on plugin/step/command/command.go
> +		}
formatting seems off here

2022-02-05 23:25 UTC, gogsbread approved these changes
code looks good, however there are some formatting issues in the file. Please run `go fmt` before completing the PR.

2022-02-09 07:52 UTC, merged